### ISSUE TITLE
Not compatible with Python 3.10 (cannot import name 'Mapping' from 'collections')

### ISSUE THREAD

**Issue by wolfgang42** [syrusakbary/pyjade#293]
This was apparently [a deprecated alias which was removed in Python 3.10](https://github.com/python/cpython/issues/81505); the new way of doing it is <code>collections<ins>.abc</ins></code>.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyjade/runtime.py", line 8, in <module>
    from collections import Mapping as MappingType
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  [...]
  File "/usr/local/lib/python3.10/site-packages/pyjade/runtime.py", line 10, in <module>
    import UserDict
ModuleNotFoundError: No module named 'UserDict'
```

Workaround: use Python 3.9 instead.

**Comment by Ucag** [comment]
您好，我是李冬，您发来的邮件已收到，我将会尽快回复您

**Comment by fatsen** [comment]
Open the folder of pyjade, and open runtime.py, then change `from collections import Mapping as MappingType` into `from collections.abc import Mapping as MappingType`. This problem solved, and it works ok for python 3.11.8. I don't know the reason, for i got this solution from my python teacher.

**Comment by wolfgang42** [comment]
@fatsen Your (teacher’s) change works because `Mapping` was moved from `collections` to `collections.abc` in Python 3.3.

However, do note that editing the source code of a library in the files that were installed is generally considered a bad idea: it will work on your computer, but is confusing when you come back to the program later when you have forgotten you did that, and is hard to keep track of if you ever give the program to someone else.

**Comment by usamamashkoor** [comment]
Did anyone find any solution for this?
